repos:
  # --- PYTHON LINTING ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # --- SHELL SCRIPTS ---
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/mvdan/sh
    rev: v3.8.0
    hooks:
      - id: shfmt

  # --- JAVASCRIPT / TYPESCRIPT ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|json|md|css|scss)$

  - repo: local
    hooks:
      - id: eslint
        name: "eslint (no-fix, fail on error)"
        entry: npx eslint .
        language: system
        types: [file]
        files: \.(js|jsx|ts|tsx)$
      - id: eslint-fix
        name: "eslint --fix (optional auto-fix)"
        entry: npx eslint . --fix
        language: system
        types: [file]
        files: \.(js|jsx|ts|tsx)$
        # Uncomment if you want auto-fix in pre-commit
        # If you want only to check, comment this block

      - id: tsc
        name: "tsc typecheck"
        entry: npx tsc --noEmit --skipLibCheck
        language: system
        types: [file]
        files: \.(ts|tsx)$
